import 'dart:ui';

import 'package:expirationdate_reminder/utils/data_utils.dart';
import 'package:expirationdate_reminder/utils/db_utils.dart';
import 'package:expirationdate_reminder/utils/notification.dart';
import 'package:intl/intl.dart';

Notification notification = Notification();
Color mainColor = const Color(0xff6699CC);

/// refrigerator
List<String> storageList = ['냉장', '냉동', '실온'];

List<Category> categoryList = [
  Category(imagePath: 'assets/images/color1.png', name: '과일', lists: fruitList),
  Category(imagePath: 'assets/images/color2.png', name: '채소', lists: vegetableList),
  Category(imagePath: 'assets/images/color3.png', name: '고기', lists: meatList),
  Category(imagePath: 'assets/images/color4.png', name: '생선', lists: fisheryList),
  Category(imagePath: 'assets/images/color5.png', name: '조개', lists: shellList),
  Category(imagePath: 'assets/images/color6.png', name: '통조림', lists: cannedFoodList),
  Category(imagePath: 'assets/images/color7.png', name: '유제품', lists: diaryProductList),
  Category(imagePath: 'assets/images/color8.png', name: '콩', lists: beenList),
  Category(imagePath: 'assets/images/color9.png', name: '견과류', lists: nutsList),
  Category(imagePath: 'assets/images/color10.png', name: '과자/간식', lists: snackList),
  Category(imagePath: 'assets/images/color11.png', name: '소스', lists: sauceList),
  Category(imagePath: 'assets/images/color12.png', name: '기타', lists: etcList),
];

List<Category> fruitList =
    List.generate(fruit.length, (index) => Category(imagePath: 'assets/images/color1.png', name: fruit[index]));
List<Category> vegetableList =
    List.generate(vegetable.length, (index) => Category(imagePath: 'assets/images/color2.png', name: vegetable[index]));
List<Category> meatList =
    List.generate(meat.length, (index) => Category(imagePath: 'assets/images/color3.png', name: meat[index]));
List<Category> fisheryList =
    List.generate(fishery.length, (index) => Category(imagePath: 'assets/images/color4.png', name: fishery[index]));
List<Category> shellList =
    List.generate(shell.length, (index) => Category(imagePath: 'assets/images/color5.png', name: shell[index]));
List<Category> cannedFoodList =
    List.generate(cannedFood.length, (index) => Category(imagePath: 'assets/images/color6.png', name: cannedFood[index]));
List<Category> diaryProductList =
    List.generate(diaryProduct.length, (index) => Category(imagePath: 'assets/images/color7.png', name: diaryProduct[index]));
List<Category> beenList =
    List.generate(been.length, (index) => Category(imagePath: 'assets/images/color8.png', name: been[index]));
List<Category> nutsList =
    List.generate(nuts.length, (index) => Category(imagePath: 'assets/images/color9.png', name: nuts[index]));
List<Category> snackList =
    List.generate(snack.length, (index) => Category(imagePath: 'assets/images/color10.png', name: snack[index]));
List<Category> sauceList =
    List.generate(sauce.length, (index) => Category(imagePath: 'assets/images/color11.png', name: sauce[index]));
List<Category> etcList = List.generate(etc.length, (index) => Category(imagePath: 'assets/images/color12.png', name: etc[index]));

List fruit = [
  '금귤',
  '구기자',
  '매실',
  '무화과',
  '체리',
  '복분자',
  '복숭아',
  '블랙베리',
  '블루베리',
  '산딸기',
  '살구',
  '앵두',
  '자두',
  '천도복숭아',
  '포도',
  '샤인머스켓',
  '거봉',
  '청포도',
  '감',
  '대추',
  '머루',
  '모과',
  '무화과',
  '배',
  '사과',
  '석류',
  '귤',
  '낑깡',
  '유자',
  '레드향',
  '천혜향',
  '한라봉',
  '구아바',
  '두리안',
  '라임',
  '람부탄',
  '레몬',
  '망고',
  '망고스틴',
  '바나나',
  '아보카도',
  '오렌지',
  '올리브',
  '용과',
  '자몽',
  '칼라만시',
  '코코넛',
  '키위',
  '크랜베리',
  '파인애플',
  '파파야',
  '패션프루트',
  '참외',
  '딸기',
  '수박',
  '멜론'
];

List vegetable = [
  '가시상추',
  '가지',
  '감자',
  '갓',
  '고구마',
  '고들빼기',
  '고사리',
  '곰보배추',
  '공심채',
  '궁채',
  '근대',
  '냉이',
  '늙은호박',
  '당근',
  '더덕',
  '도라지',
  '돌나물',
  '돼지감자',
  '두릅',
  '락교',
  '로메인상추',
  '마',
  '명아주',
  '무',
  '무청',
  '밤',
  '방울토마토',
  '배추',
  '브로콜리',
  '비트',
  '사탕수수',
  '산마늘',
  '상추',
  '숙주나물',
  '순무',
  '시금치',
  '시래기',
  '쌈추',
  '쑥',
  '쑥갓',
  '아스파라거스',
  '아욱',
  '알타리무',
  '애호박',
  '양배추',
  '양상추',
  '연근',
  '열무',
  '오이',
  '옥수수',
  '우거지',
  '우엉',
  '자차이',
  '장생도라지',
  '죽순',
  '쪽파',
  '청경채',
  '치커리',
  '카사바',
  '케일',
  '콜라비',
  '콜리플라워',
  '콩나물',
  '콩',
  '토란',
  '토마토',
  '파슬리',
  '파프리카',
  '피망',
  '호박',
  '호박고구마',
];

List meat = [
  '소고기',
  '목심',
  '척아이롤',
  '등심',
  '살치살',
  '새우살',
  '립아이',
  '토마호크',
  '채끝',
  '안심',
  'T본',
  '우둔',
  '홍두깨살',
  '앞다리',
  '부챗살',
  '갈비',
  'LA갈비',
  '우대갈비',
  '안창살',
  '설도',
  '도가니살',
  '양지',
  '차돌박이',
  '우삼겹',
  '업진살',
  '치마살',
  '사태',
  '아롱사태',
  '우족',
  '돼지고기',
  '돼지머리',
  '목살',
  '가브리살',
  '등심',
  '뒷다리살',
  '항정살',
  '갈비',
  '갈매기살',
  '안심',
  '앞다리살',
  '삼겹살',
  '돈족',
  '돼지곱창',
  '오소리감투',
  '돼지껍데기',
  '선지',
  '베이컨',
  '소시지',
  '순대',
  '햄',
  '닭고기',
  '닭모가지',
  '닭가슴살',
  '닭봉',
  '닭날개',
  '닭넓적다리',
  '닭다리',
  '닭발',
  '닭껍질',
  '닭똥집',
  '양고기',
  '양갈비',
  '말고기',
  '개고기'
];

List fishery = [
  '가다랑어',
  '가물치',
  '가오리',
  '가자미',
  '갈치',
  '감성돔',
  '개복치',
  '갯장어',
  '고등어',
  '광어',
  '넙치',
  '꼼장어',
  '꽁치',
  '날치',
  '노래미',
  '농어',
  '능성어',
  '대구',
  '도다리',
  '도루묵',
  '도미',
  '돌돔',
  '돔배기',
  '메기',
  '멸치',
  '명태',
  '물메기',
  '미꾸라지',
  '민어',
  '방어',
  '뱅어',
  '벵에돔',
  '병어',
  '보리멸',
  '복어',
  '볼기우럭',
  '볼락',
  '빙어',
  '산천어',
  '삼치',
  '송어',
  '숭어',
  '쏘가리',
  '쏨뱅이',
  '아귀',
  '연어',
  '우럭',
  '은어',
  '임연수어',
  '자갈치',
  '장어',
  '전갱이',
  '전어',
  '조기',
  '쥐치',
  '참돔',
  '참치',
  '청새치',
  '청어',
  '향어',
  '홍어',
];

List shell = [
  '가리비',
  '개량조개',
  '개조개',
  '거거',
  '굴',
  '꼬막',
  '대칭이',
  '동죽',
  '맛조개',
  '모시조개',
  '바지락',
  '백합',
  '재첩',
  '키조개',
  '피조개',
  '홍합',
  '개오지',
  '골뱅이',
  '달팽이',
  '나팔고둥',
  '소라',
  '전복'
];

List cannedFood = ['참치캔', '고추참치캔', '야채참치캔', '스팸', '런천미트', '리챔', '백도복숭아캔', '황도복숭아캔', '골뱅이캔', '번데기캔'];
List diaryProduct = [
  '우유',
  '생크림',
  '휘핑크림',
  '버터',
  '아이스크림',
  '카이막',
  '요거트',
  '그릭요거트',
  '크림치즈',
  '체다치즈',
  '모짜렐라치즈',
  '슬라이스치즈',
  '연유',
  '분유',
  '요구르트',
  '야구르트'
];

List been = ['강낭콩', '구마', '녹두', '대두', '땅콩', '렌틸', '병아리콩', '서리태', '완두', '작두콩', '커피땅콩', '팥', '풋콩'];
List nuts = [
  '가래',
  '갈릭넛',
  '도토리',
  '마카다미아',
  '밤',
  '브라질너트',
  '아몬드',
  '은행',
  '잣',
  '피스타치오',
  '피칸',
  '헤이즐넛',
  '호두',
  '사차인치',
  '사푸카야',
  '세루',
  '과야키',
  '캐슈넛',
  '호'
];

List snack = ['과자', '시리얼', '빵', '케이크', '조각케이크', '떡', '껌', '쿠키', '사탕', '초콜렛', '젤리', '푸딩', '캐러멜'];
List sauce = [
  '간장',
  '국간장',
  '맛간장',
  '양조간장',
  '진간장',
  '식초',
  '고추장',
  '된장',
  '쌈장',
  '미소된장',
  '청국장',
  '물엿',
  '올리고당',
  '꿀',
  '후추',
  '소금',
  '맛소금',
  '천일염',
  '겨자',
  '고추냉이',
  '고춧가루',
  '설탕',
  '미원',
  '캡사이신',
  '다시다',
  '맛술',
  '미림',
  '액젓',
  '참치액젓',
  '멸치액젓',
  '까나리액젓',
  '육수코인',
  '파스타소스',
  '칠리소스',
  '살사소스',
  '머스터드',
  '굴소스',
  '드레싱',
  '돈까스소스',
  '스테이크소스',
  '케첩',
  '마요네즈'
];

List etc = ['라면', '비빔면', '국수', '냉면'];

List colors = [
  'assets/images/color1.png',
  'assets/images/color2.png',
  'assets/images/color3.png',
  'assets/images/color4.png',
  'assets/images/color5.png',
  'assets/images/color6.png',
  'assets/images/color7.png',
  'assets/images/color8.png',
  'assets/images/color9.png',
  'assets/images/color10.png',
  'assets/images/color11.png',
  'assets/images/color12.png',
  'assets/images/color13.png',
  'assets/images/color14.png',
  'assets/images/color15.png',
  'assets/images/color16.png',
  'assets/images/color17.png',
  'assets/images/color18.png',
  'assets/images/color19.png',
  'assets/images/color20.png',
  'assets/images/color21.png',
  'assets/images/color22.png',
  'assets/images/color23.png',
];

/// alert
enum AlertType { REMAIN_ALERT, PAST_ALERT }

/// setting
List<String> expirationMarkList = ['D-Day', DateFormat('yy.MM.dd').format(DateTime.now())];
